spring:
  application:
    name: Sanguosha1v1
  main:
    allow-circular-references: true

logging:
  level:
    root: warn
  pattern:
    console: "%msg%n"

app:
  one-config:
    name: "滕芳兰"
    hp: 3
    maxHp: 3
    hand-cards: [ ]
  two-config:
    name: "10000血白板"
    hp: 10000
    maxHp: 10000
    hand-cards: [ ]
